- name: install node
  become: true
  apt:
    name: ['nodejs', 'npm']
  tags:
  - node

- name: install n
  become: true
  npm: 
    name: n
    global: true
  tags:
  - node

- name: n 14
  become: true
  shell: n 14
  tags:
  - node
