- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  tags:
  - rust

- name: install rust
  when: cargo_exists is failed
  #when: "'FAILED' in cargo_exists.stderr"
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rust-installer.sh && chmod +x /tmp/rust-installer.sh && /tmp/rust-installer.sh -y
  tags: 
  - rust

- name: prerequisites
  become: true
  apt:
    name: ["cmake", "libfontconfig1-dev"]
    tags:
      - rust

- name: install alacritty
  shell: . /home/marcos/.cargo/env && cargo install alacritty
  tags:
    - rust
